const express = require('express');
const asyncHandler = require('../middleware/asyncHandler');
const { requireAuth, requirePermission } = require('../middleware/auth');
const auditLogger = require('../middleware/auditLogger');
const { imageUpload } = require('../middleware/upload');
const controller = require('../controllers/admin.controller');

const router = express.Router();
router.use(requireAuth('admin'));
router.use(auditLogger);
router.post('/uploads', imageUpload.single('file'), asyncHandler(controller.uploadMedia));
router.get('/profile', asyncHandler(controller.profile));
router.put('/profile', asyncHandler(controller.updateProfile));
router.get('/dashboard', requirePermission('dashboard.view'), asyncHandler(controller.dashboard));
router.get('/settings', requirePermission('settings.manage'), asyncHandler(controller.settings));
router.put('/settings/:key', requirePermission('settings.manage'), asyncHandler(controller.updateSetting));
router.get('/remote-config', requirePermission('remote_config.manage'), asyncHandler(controller.listRemoteConfig));
router.post('/remote-config', requirePermission('remote_config.manage'), asyncHandler(controller.createRemoteConfig));
router.put('/remote-config/:configId', requirePermission('remote_config.manage'), asyncHandler(controller.updateRemoteConfig));
router.get('/audit-logs', requirePermission('audit_logs.view'), asyncHandler(controller.listAuditLogs));
router.get('/audit-logs/:auditLogId', requirePermission('audit_logs.view'), asyncHandler(controller.getAuditLog));
router.get('/admin-roles', requirePermission('admin_users.view'), asyncHandler(controller.listAdminRoles));
router.get('/admin-roles/:roleId', requirePermission('admin_users.view'), asyncHandler(controller.getAdminRole));
router.get('/permissions', requirePermission('admin_users.view'), asyncHandler(controller.listPermissions));
router.get('/vehicle-categories', requirePermission('vehicle_categories.manage'), asyncHandler(controller.listVehicleCategories));
router.get('/vehicle-categories/:categoryId', requirePermission('vehicle_categories.manage'), asyncHandler(controller.getVehicleCategory));
router.post('/vehicle-categories', requirePermission('vehicle_categories.manage'), asyncHandler(controller.saveVehicleCategory));
router.put('/vehicle-categories/:categoryId', requirePermission('vehicle_categories.manage'), asyncHandler(controller.saveVehicleCategory));
router.delete('/vehicle-categories/:categoryId', requirePermission('vehicle_categories.manage'), asyncHandler(controller.deleteVehicleCategory));
router.post('/devices', asyncHandler(controller.registerAdminDevice));
router.get('/reports', requirePermission('reports.view'), asyncHandler(controller.reports));
router.get('/trip-reviews', requirePermission('reviews.approve'), asyncHandler(controller.listReviews));
router.get('/enquiries', requirePermission('customers.manage'), asyncHandler(controller.listEnquiries));
router.get('/enquiries/:enquiryId', requirePermission('customers.manage'), asyncHandler(controller.getEnquiry));
router.put('/enquiries/:enquiryId', requirePermission('customers.manage'), asyncHandler(controller.updateEnquiry));
router.get('/notifications', requirePermission('notifications.send'), asyncHandler(controller.listNotifications));
router.delete('/notifications/:notificationId', requirePermission('notifications.send'), asyncHandler(controller.deleteNotification));
router.get('/admin-users', requirePermission('admin_users.view'), asyncHandler(controller.listAdminUsers));
router.get('/admin-users/:adminUserId', requirePermission('admin_users.view'), asyncHandler(controller.getAdminUser));
router.post('/admin-users', requirePermission('admin_users.manage'), asyncHandler(controller.saveAdminUser));
router.put('/admin-users/:adminUserId', requirePermission('admin_users.manage'), asyncHandler(controller.saveAdminUser));
router.post('/admin-users/:adminUserId/activate', requirePermission('admin_users.manage'), asyncHandler(controller.activateAdminUser));
router.post('/admin-users/:adminUserId/deactivate', requirePermission('admin_users.manage'), asyncHandler(controller.deactivateAdminUser));
router.get('/routes', requirePermission('routes.manage'), asyncHandler(controller.listRoutes));
router.get('/cities', requirePermission('routes.manage'), asyncHandler(controller.listAdminCities));
router.get('/routes/:routeId', requirePermission('routes.manage'), asyncHandler(controller.getRoute));
router.post('/routes', requirePermission('routes.manage'), asyncHandler(controller.saveRoute));
router.put('/routes/:routeId', requirePermission('routes.manage'), asyncHandler(controller.saveRoute));
router.delete('/routes/:routeId', requirePermission('routes.manage'), asyncHandler(controller.deleteRoute));
router.get('/tariffs', requirePermission('tariff.manage'), asyncHandler(controller.listTariffs));
router.get('/tariffs/:tariffId', requirePermission('tariff.manage'), asyncHandler(controller.getTariff));
router.post('/tariffs', requirePermission('tariff.manage'), asyncHandler(controller.saveTariff));
router.put('/tariffs/:tariffId', requirePermission('tariff.manage'), asyncHandler(controller.saveTariff));
router.delete('/tariffs/:tariffId', requirePermission('tariff.manage'), asyncHandler(controller.deleteTariff));
router.get('/faqs', requirePermission('faq.manage'), asyncHandler(controller.listFaqs));
router.get('/faqs/:faqId', requirePermission('faq.manage'), asyncHandler(controller.getFaq));
router.post('/faqs', requirePermission('faq.manage'), asyncHandler(controller.saveFaq));
router.put('/faqs/:faqId', requirePermission('faq.manage'), asyncHandler(controller.saveFaq));
router.delete('/faqs/:faqId', requirePermission('faq.manage'), asyncHandler(controller.deleteFaq));
router.get('/gallery', requirePermission('gallery.manage'), asyncHandler(controller.listGallery));
router.post('/gallery/groups', requirePermission('gallery.manage'), asyncHandler(controller.createGalleryGroup));
router.post('/gallery/images', requirePermission('gallery.manage'), asyncHandler(controller.createGalleryImage));
router.put('/gallery/images/:imageId', requirePermission('gallery.manage'), asyncHandler(controller.updateGalleryImage));
router.delete('/gallery/groups/:recordId', requirePermission('gallery.manage'), (req, res, next) => { req.params.recordType = 'group'; next(); }, asyncHandler(controller.deleteGalleryRecord));
router.delete('/gallery/images/:recordId', requirePermission('gallery.manage'), (req, res, next) => { req.params.recordType = 'image'; next(); }, asyncHandler(controller.deleteGalleryRecord));
router.get('/reviews', requirePermission('reviews.approve'), asyncHandler(controller.listReviewsAdmin));
router.get('/reviews/:reviewId', requirePermission('reviews.approve'), asyncHandler(controller.getReview));
router.post('/reviews', requirePermission('reviews.approve'), asyncHandler(controller.saveReview));
router.put('/reviews/:reviewId', requirePermission('reviews.approve'), asyncHandler(controller.saveReview));
router.delete('/reviews/:reviewId', requirePermission('reviews.approve'), asyncHandler(controller.deleteReview));
router.post('/reviews/:reviewId/:action(approve|reject)', requirePermission('reviews.approve'), asyncHandler(controller.moderateReview));
router.get('/vehicles', requirePermission('vehicles.manage'), asyncHandler(controller.listVehicles));
router.get('/vehicles/:vehicleId', requirePermission('vehicles.manage'), asyncHandler(controller.getVehicle));
router.post('/vehicles', requirePermission('vehicles.manage'), asyncHandler(controller.saveVehicle));
router.put('/vehicles/:vehicleId', requirePermission('vehicles.manage'), asyncHandler(controller.saveVehicle));
router.delete('/vehicles/:vehicleId', requirePermission('vehicles.manage'), asyncHandler(controller.deleteVehicle));
router.get('/driver-assignments', requirePermission('driver_assignments.manage'), asyncHandler(controller.listAssignments));
router.get('/driver-assignments/:assignmentId', requirePermission('driver_assignments.manage'), asyncHandler(controller.listAssignments));
router.post('/driver-assignments', requirePermission('driver_assignments.manage'), asyncHandler(controller.createAssignment));
router.post('/driver-assignments/:assignmentId/end', requirePermission('driver_assignments.manage'), asyncHandler(controller.endAssignment));
router.get('/bookings', requirePermission('bookings.view'), asyncHandler(controller.listBookings));
router.get('/bookings/:bookingId', requirePermission('bookings.view'), asyncHandler(controller.getBooking));
router.get('/bookings/:bookingId/payment', requirePermission('bookings.view'), asyncHandler(controller.getBookingPayment));
router.post('/bookings/:bookingId/payment', requirePermission('bookings.update'), asyncHandler(controller.recordBookingPayment));
router.put('/bookings/:bookingId/payment-status', requirePermission('bookings.update'), asyncHandler(controller.setBookingPaymentStatus));
router.get('/bookings/:bookingId/invoice/pdf', requirePermission('bookings.view'), asyncHandler(controller.downloadBookingInvoice));
router.post('/bookings/:bookingId/invoice/resend', requirePermission('bookings.view'), asyncHandler(controller.resendBookingInvoice));
router.post('/bookings/:bookingId/confirm', requirePermission('bookings.update'), asyncHandler(controller.confirmBooking));
router.post('/bookings/:bookingId/reject', requirePermission('bookings.update'), asyncHandler(controller.rejectBooking));
router.post('/bookings/:bookingId/cancel', requirePermission('bookings.cancel'), asyncHandler(controller.cancelBooking));
router.post('/bookings/:bookingId/assign-driver', requirePermission('driver_offers.manage'), asyncHandler(controller.assignDriver));
router.get('/customers', requirePermission('customers.view'), asyncHandler(controller.listCustomers));
router.get('/customers/:customerId', requirePermission('customers.view'), asyncHandler(controller.getCustomer));
router.get('/drivers', requirePermission('drivers.view'), asyncHandler(controller.listDrivers));
router.get('/drivers/:driverId', requirePermission('drivers.view'), asyncHandler(controller.getDriver));
router.post('/drivers', requirePermission('drivers.manage'), asyncHandler(controller.saveDriver));
router.put('/drivers/:driverId', requirePermission('drivers.manage'), asyncHandler(controller.saveDriver));
router.post('/drivers/:driverId/photo', requirePermission('drivers.manage'), imageUpload.single('file'), asyncHandler(controller.uploadDriverPhoto));
router.delete('/drivers/:driverId', requirePermission('drivers.manage'), asyncHandler(controller.deleteDriver));

module.exports = router;