const express = require('express');
const asyncHandler = require('../middleware/asyncHandler');
const { requireAuth } = require('../middleware/auth');
const controller = require('../controllers/customer.controller');
const publicController = require('../controllers/public.controller');

const router = express.Router();
router.use(requireAuth('customer'));
router.get('/profile', asyncHandler(controller.profile));
router.put('/profile', asyncHandler(controller.updateProfile));
router.get('/saved-places', asyncHandler(controller.listSavedPlaces));
router.post('/saved-places', asyncHandler(controller.createSavedPlace));
router.put('/saved-places/:savedPlaceId', asyncHandler(controller.updateSavedPlace));
router.delete('/saved-places/:savedPlaceId', asyncHandler(controller.deleteSavedPlace));
router.get('/bookings', asyncHandler(controller.listBookings));
router.post('/bookings', asyncHandler(publicController.createGuestBooking));
router.get('/bookings/:bookingId', asyncHandler(controller.getBooking));
router.post('/bookings/:bookingId/cancel', asyncHandler(controller.cancelBooking));
router.get('/bookings/:bookingId/invoice', asyncHandler(controller.getInvoice));
router.get('/bookings/:bookingId/location', asyncHandler(controller.getLiveLocation));
router.post('/bookings/:bookingId/rating', asyncHandler(controller.rateTrip));
router.get('/notifications', asyncHandler(controller.notifications));
router.post('/devices', asyncHandler(controller.registerDevice));
router.delete('/devices/:deviceId', asyncHandler(controller.deleteDevice));
router.get('/support', asyncHandler(controller.listSupport));
router.post('/support', asyncHandler(controller.createSupport));
router.get('/support/:supportId', asyncHandler(controller.getSupport));
router.post('/support/:supportId/messages', asyncHandler(controller.addSupportMessage));

module.exports = router;